channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pycodestyle
  - pip:
    - torch
    - transformers
    - dagshub
    - pytorch-lightning
    - pandas
    - s3fs
    - boto3
    - torchmetrics
    - nltk
    - datasets
